services:
  postgres:
    image: postgres:16-alpine
    container_name: fluentify-postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: fluentify
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./src/database/01-tables.sql:/docker-entrypoint-initdb.d/01-tables.sql
      - ./src/database/02-tables.sql:/docker-entrypoint-initdb.d/02-tables.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fluentify-backend
    restart: on-failure
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "5000:5000"
    environment:
      - CHOKIDAR_USEPOLLING=true
      - DATABASE_URL=${DATABASE_URL}
      - PORT=${PORT}
      - NODE_ENV=${NODE_ENV}
      - JWT_SECRET=${JWT_SECRET}
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - RETELL_API_KEY=${RETELL_API_KEY}
      - RETELL_AGENT_ID=${RETELL_AGENT_ID}
    volumes:
      - ./src:/app/src
      - /app/node_modules

volumes:
  postgres_data:
