services:
  postgres:
    image: postgres:16-alpine
    container_name: fluentify-postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: fluentify
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./src/database/01-tables.sql:/docker-entrypoint-initdb.d/01-tables.sql
      - ./src/database/02-tables.sql:/docker-entrypoint-initdb.d/02-tables.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fluentify-backend
    restart: on-failure
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "5000:5000"
    env_file:
      - .env
    environment:
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ./src:/app/src
      - /app/node_modules

volumes:
  postgres_data:
