import { GoogleGenerativeAI } from '@google/generative-ai';
import db from '../config/db.js';
import knowledgeGraphRepository from '../repositories/knowledgeGraphRepository.js';

/**
 * Remedial Generation Service — Phase 9 (Case 2)
 *
 * Triggered when A* detects a weak concept (mastery < 0.5) whose linked
 * lessons have all already been completed. A compact, focused mini-lesson
 * is generated by Gemini and stored in course_lessons with is_remedial=TRUE
 * so the learner can re-engage with exactly the weak area.
 *
 * This service is always called fire-and-forget — it never blocks the
 * recommendation API response.
 */
class RemedialGenerationService {
  constructor() {
    if (!process.env.GEMINI_API_KEY) {
      console.warn('GEMINI_API_KEY not set. Remedial generation will be disabled.');
      this.model = null;
      return;
    }
    const genAI = new GoogleGenerativeAI(process.env.GEMINI_API_KEY);
    this.model = genAI.getGenerativeModel({ model: 'gemini-2.0-flash' });
  }

  /**
   * Check and generate a remedial lesson for a concept if needed.
   *
   * Conditions for generation:
   *  1. Concept mastery < 0.5 (weak)
   *  2. All lessons linked to this concept are already completed by the learner
   *  3. No existing remedial lesson already created for this concept
   *
   * @param {number} learnerId
   * @param {number} courseId
   * @param {Object} concept    — enriched node from buildGraph (id, conceptLabel, conceptType, masteryScore, lessonDbId)
   */
  async checkAndGenerate(learnerId, courseId, concept) {
    if (!this.model) return;
    if (concept.masteryScore >= 0.5) return;

    try {
      // Guard: skip if remedial already exists for this concept
      const existing = await knowledgeGraphRepository.findExistingRemedialLesson(
        courseId, concept.id
      );
      if (existing) return;

      // Guard: only generate if the linked lesson has been completed by this learner
      if (concept.lessonDbId) {
        const completedCheck = await db.query(
          `SELECT 1 FROM lesson_progress
           WHERE learner_id = $1 AND lesson_id = $2 AND is_completed = TRUE
           LIMIT 1`,
          [learnerId, concept.lessonDbId]
        );
        if (completedCheck.rowCount === 0) return; // lesson not done yet — normal flow handles it
      }

      // Fetch course language for the prompt
      const courseRow = await db.query(
        'SELECT language FROM courses WHERE id = $1',
        [courseId]
      );
      const language = courseRow.rows[0]?.language ?? 'the target language';

      console.log(`📝 Generating remedial lesson for concept "${concept.conceptLabel}" (course ${courseId})...`);

      // Resolve the unit_id for the concept's lesson so saveRemedialLesson can place the row
      let unitDbId = null;
      if (concept.lessonDbId) {
        const unitRow = await db.query(
          'SELECT unit_id FROM course_lessons WHERE id = $1 LIMIT 1',
          [concept.lessonDbId]
        );
        unitDbId = unitRow.rows[0]?.unit_id ?? null;
      }
      if (!unitDbId) {
        // Fallback: use the first unit of the course
        const fallback = await db.query(
          'SELECT DISTINCT unit_id FROM course_lessons WHERE course_id = $1 ORDER BY unit_id LIMIT 1',
          [courseId]
        );
        unitDbId = fallback.rows[0]?.unit_id ?? 1;
      }

      const lessonContent = await this.generateRemedialContent(concept, language);
      if (!lessonContent) return;

      // Map Gemini output fields to repository-expected shape
      const lessonData = {
        title:            lessonContent.title,
        type:             concept.conceptType,
        description:      lessonContent.explanation ?? '',
        vocabulary:       concept.conceptType === 'vocabulary' ? [lessonContent.explanation] : [],
        grammarPoints:    concept.conceptType === 'grammar'    ? lessonContent.keyPoints     : [],
        exercises:        (lessonContent.exercises ?? []).map(e => ({
                            question:  e.question,
                            answer:    e.answer,
                            hint:      e.hint,
                            type:      'short_answer',
                          })),
        estimatedDuration: 10,
        xpReward:          40,
      };

      await knowledgeGraphRepository.saveRemedialLesson(courseId, unitDbId, concept.id, lessonData);

      console.log(`✅ Remedial lesson saved for concept "${concept.conceptLabel}"`);
    } catch (err) {
      // Always fail silently — remedial generation is a background enhancement
      console.error(`Remedial generation failed for concept ${concept.id}:`, err.message);
    }
  }

  /**
   * Call Gemini to produce a compact focused mini-lesson JSON.
   */
  async generateRemedialContent(concept, language) {
    const prompt = `You are a language teaching assistant. A learner is struggling with the following concept in ${language}.

Concept: "${concept.conceptLabel}"
Type: ${concept.conceptType}
Current mastery: ${Math.round(concept.masteryScore * 100)}% (needs improvement)

Generate a short, focused remedial mini-lesson as JSON. The lesson should:
- Target exactly this concept's weak area
- Be concise (3-5 minutes to complete)
- Include 2-3 clear explanation points
- Include 3 simple practice exercises with answers

Return ONLY valid JSON in this exact structure:
{
  "title": "Remedial: <concept name>",
  "focusConcept": "${concept.conceptLabel}",
  "conceptType": "${concept.conceptType}",
  "explanation": "Brief 2-3 sentence explanation of the concept",
  "keyPoints": ["point 1", "point 2", "point 3"],
  "exercises": [
    { "question": "...", "answer": "...", "hint": "..." },
    { "question": "...", "answer": "...", "hint": "..." },
    { "question": "...", "answer": "...", "hint": "..." }
  ],
  "encouragement": "Short motivating message for the learner"
}`;

    try {
      const result = await this.model.generateContent({
        contents: [{ role: 'user', parts: [{ text: prompt }] }],
        generationConfig: { maxOutputTokens: 1024, temperature: 0.6 },
      });

      const raw = result.response.text().trim();
      return this.parseRemedialJSON(raw, concept);
    } catch (err) {
      console.error('Gemini remedial generation error:', err.message);
      return null;
    }
  }

  /**
   * Robust JSON parser — handles markdown code fences and trailing commas.
   */
  parseRemedialJSON(raw, concept) {
    let text = raw;

    // Strip markdown fences
    text = text.replace(/^```(?:json)?\s*/i, '').replace(/\s*```\s*$/i, '').trim();

    // Fix trailing commas (common Gemini quirk)
    text = text.replace(/,\s*([\]}])/g, '$1');

    try {
      return JSON.parse(text);
    } catch {
      // Fallback: build a minimal remedial lesson so we never lose the attempt
      return {
        title:          `Remedial: ${concept.conceptLabel}`,
        focusConcept:   concept.conceptLabel,
        conceptType:    concept.conceptType,
        explanation:    `Review and practise ${concept.conceptLabel} to improve your mastery.`,
        keyPoints:      [`Focus on ${concept.conceptLabel}`, 'Practice regularly', 'Ask the AI chatbot for help'],
        exercises:      [],
        encouragement:  'Keep going — you\'re making progress!',
      };
    }
  }
}

export default new RemedialGenerationService();
